# file: openbao-cert.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openbao-tls
  namespace: openbao
spec:
  secretName: openbao-server-tls # Name of the K8s Secret where cert+key will be stored
  issuerRef:
    name: my-ca-clusterissuer # Reference to the Issuer you created above
    kind: ClusterIssuer
  commonName: openbao.openbao.svc.cluster.local
  dnsNames:
    - openbao
    - openbao.openbao.svc
    - openbao.openbao.svc.cluster.local
  duration: 2160h # > 90 days, optional
  privateKey:
    algorithm: RSA
    size: 2048
