apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: openbao-connection
  namespace: vault-secrets-operator
spec:
  address: "http://openbao.openbao.svc.cluster.local:8200"
