apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: openbao-connection
  namespace: vault-secrets-operator
spec:
  address: "https://openbao.openbao.svc.cluster.local:8200"
  skipTLSVerify: false

  caCertSecretRef:
    name: openbao-ca-bundle
    key: ca.crt
