apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mydb-credentials
  namespace: vault-secrets-operator
spec:
  vaultAuthRef: openbao-auth
  mount: secret # KV v1 mount path (typically 'secret')
  type: kv-v2 # Important: specify kv-v1
  path: db-creds # Full path is 'secret/db-creds'
  destination:
    create: true
    name: mydb-root-secret # This will be the name of the K8s Secret created
