apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
  namespace: default
spec:
  secretName: test-cert-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: <subdomain.your-domain.com> # e.g., test.example.com
  dnsNames:
    - <subdomain.your-domain.com>
