apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-ui-cert
  namespace: vault
spec:
  secretName: vault-ui-tls
  duration: 2160h # 90d
  renewBefore: 360h
  commonName: vault.local
  dnsNames:
    - vault.local
  issuerRef:
    name: vault-ca-issuer # <- use your actual issuer
    kind: ClusterIssuer
