# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: vault-ca
#   namespace: vault
# spec:
#   isCA: true
#   commonName: vault-ca
#   secretName: tls-ca
#   duration: 8760h # 1 year
#   issuerRef:
#     name: vault-ca-issuer
#     kind: ClusterIssuer

---
# Claude
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-ca-tls
  namespace: vault
spec:
  secretName: tls-ca
  issuerRef:
    name: vault-ca-issuer
    kind: ClusterIssuer
  commonName: Vault CA
  isCA: true
  duration: 8760h
  renewBefore: 720h
