apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: my-ca-secret
  namespace: cert-manager
type: kubernetes.io/tls
data:
  tls.crt: <BASE64_ENCODED_CERTIFICATE>
  tls.key: <BASE64_ENCODED_PRIVATE_KEY>
