apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb-sa
  namespace: mariadb-prod
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-sa # arbitrary name for this Secret
  namespace: mariadb-prod # must match the SA’s namespace
  annotations:
    kubernetes.io/service-account.name: "mariadb-sa"
type: kubernetes.io/service-account-token
