apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: mariadb-vault-connection
  namespace: mariadb-prod
spec:
  # HTTP
  address: http://openbao.openbao.svc.cluster.local:8200
  skipTLSVerify: true

  # HTTPS
  # address: https://openbao.openbao.svc.cluster.local:8200
  # caCertSecretRef: openbao-ca-bundle
  # skipTLSVerify: false
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: mariadb-vault-auth
  namespace: mariadb-prod
spec:
  vaultConnectionRef: mariadb-vault-connection # <- Reference to VaultConnection CR
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: mariadb-role
    serviceAccount: mariadb-sa
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mariadb-secret-staticsecret
  namespace: mariadb-prod
spec:
  vaultAuthRef: mariadb-vault-auth # <- Reference to VaultAuth CR
  mount: secret # <- This is the Vault mount (e.g. "kv")
  path: mariadb/prod # <- Full path to the secret
  type: kv-v2 # <- Type of Vault secret engine

  destination:
    create: true
    name: mariadb-k8s-secret # <- The Kubernetes Secret name to create
