apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: openbao-selfsigned-root
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openbao-ca
  namespace: cert-manager
spec:
  isCA: true
  secretName: openbao-ca-secret
  commonName: openbao-ca
  issuerRef:
    name: openbao-selfsigned-root
    kind: ClusterIssuer
