apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openbao-server-tls
  namespace: openbao
spec:
  secretName: openbao-server-tls
  dnsNames:
    - "openbao-internal"
    - "openbao-internal.openbao"
    - "openbao-internal.openbao.svc"
    - "openbao-internal.openbao.svc.cluster.local"
    - "*.openbao-internal.openbao.svc.cluster.local"
    - "openbao.openbao.svc.cluster.local"
  issuerRef:
    name: openbao-ca-issuer
    kind: ClusterIssuer
