apiVersion: v1
kind: Secret
metadata:
  name: bao-client-token
  namespace: openbao
type: Opaque
stringData:
  VAULT_TOKEN: <LOGIN-TOKEN> # Replace with your actual token
---
apiVersion: v1
kind: Pod
metadata:
  name: bao-svc-client
  namespace: openbao
spec:
  containers:
    - name: bao
      image: quay.io/openbao/openbao:2.2.2
      command: ["sh"]
      args: ["-c", "sleep infinity"]
      env:
        - name: VAULT_ADDR
          # service dns name used after unsealing & joining
          value: "https://openbao.openbao.svc.cluster.local:8200"
        - name: VAULT_CACERT
          value: "/openbao/ca/tls.crt"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: bao-client-token
              key: VAULT_TOKEN
      volumeMounts:
        - name: bao-ca
          mountPath: /openbao/ca
  volumes:
    - name: bao-ca
      secret:
        secretName: openbao-ca-secret
