apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mariadb-galera-cert
  namespace: mariadb-galera-prod # Replace this!
spec:
  secretName: mariadb-galera-tls-secret # This is the secret your Helm chart expects
  issuerRef:
    name: my-ca-clusterissuer # Your cluster-wide issuer
    kind: ClusterIssuer
  commonName: mariadb-galera.mariadb-galera-prod.svc # Replace with your MariaDB service FQDN
  dnsNames:
    - mariadb-galera
    - mariadb-galera.mariadb-galera-prod
    - mariadb-galera.mariadb0galera-prod.svc
  usages:
    - digital signature
    - key encipherment
    - server auth
