---
apiVersion: v1
kind: Namespace
metadata:
  name: app1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app1-sa
  namespace: app1
---
apiVersion: v1
kind: Secret
metadata:
  name: app1-sa
  namespace: app1
  annotations:
    # Tells K8s to populate this Secret with the 'app1-sa' ServiceAccount’s token
    kubernetes.io/service-account.name: app1-sa
type: kubernetes.io/service-account-token
